server:
  address: localhost
  port: 9527
  servlet:
    context-path: /openapi
spring:
  profiles:
    active: dev
  application:
    name: springbootopenapi
springdoc:
  api-docs:
    path: /v1/api-docs