info:
 app:
  name: MVC API
  java:
   version: 1.0.0
  type: Microservice API
management:
 endpoints:
  web:
   exposure:
    include: health,info
server:
 address: 0.0.0.0 
 port: 8083
spring:
 data:
  cassandra:
   keyspace-name: jobsmonitor
   contact-points: ubuntu-master, ubuntu-dev2