server:
  address: localhost
  port: 9527
  servlet:
    context-path: /springbootjob
spring:
  profiles:
    active: dev
  application:
    name: springbootjob
  datasource:
   url: jdbc:mysql://centos7-master:3306/springboot_job?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   username: spring
   password: springbootrestfuldev)(*&ASD12367
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   generate-ddl: true
   show-sql: true
org:
 jobrunr:
  background-job-server:
   enabled: true
  dashboard:
   enabled: true
   port: 9528