spring:
 application:
  name: springcloud-consul-producer
 cloud:
  consul:
   host: ubuntu-master
   port: 8500
   discovery:
    hostname: centos-dev1
    enabled: true
    serviceName: consul-producer
    health-check-interval: 10s
    register: true
    health-check-path: /health
    tags: owner=Kiko
server:
 port: 8502
