info:
 app:
  name: MVC API
  java:
   version: 1.0.0
  type: Microservice API
management:
 endpoints:
  web:
   exposure:
    include: health,info
server:
 address: 0.0.0.0 
 port: 8082
spring:
 jackson:
  serialization:
   FAIL_ON_EMPTY_BEANS: false
 kafka:
  consumer:
   group-id: webflux-with-latency-jetty
  bootstrap-servers: localhost:9092