spring:
 application:
  name: springcloud-consul-producer
 cloud:
  consul:
   host: ubuntu-master
   port: 8500
   discovery:
    enabled: true
    serviceName: consul-producer
    health-check-interval: 10s
    register: true
    health-check-path: /health
    tags: owner=Sillycat
server:
 port: 8501
